# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/pycaret_nbdev',
                'doc_host': 'https://castorfou.github.io',
                'git_url': 'https://github.com/castorfou/pycaret_nbdev',
                'lib_path': 'pycaret_nbdev'},
  'syms': {'pycaret_nbdev.core': {'pycaret_nbdev.core.foo': ('core.html#foo', 'pycaret_nbdev/core.py')}}}